# mainnet
# -------------------------------
[package]
name = "IntegerMate"
version = "testnet-v1.37.2"
published-at = "0x7675334bcfd81e7a3268ff0b9c8611b20c68b259c46ce840f6237d3018368cb6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
integer_mate = "0x7675334bcfd81e7a3268ff0b9c8611b20c68b259c46ce840f6237d3018368cb6"
